version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledgekeepercore_prod
    ports:
      - "6000:6000"  # Port mapping uses the .env variable
    env_file:
      - .env  # Load variables from the .env file
    volumes:
      - .:/usr/src/app
    command: npm run start  # Runs the start script