version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: >
      /bin/sh -c "
      npm run migration:run:dev &&
      npm start
      "