version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=knowledgekeeper
    depends_on:
      - postgres-db
    networks:
      - app-network
    command: >
      /bin/sh -c "
      npm run migration:run:dev &&
      npm start
      "

networks:
  app-network:
    driver: bridge