version: '3.8'

services:
  app:
    image: knowledgekeeper-core:latest
    container_name: node_app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 8g   # Adjust memory limit here (e.g., 4 GB)
          cpus: "2.0"  # Adjust CPU limit (optional)
