name: CI/CD for KnowledgeKeeperCore

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Prepare SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_hariship
        chmod 600 ~/.ssh/github_hariship
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        
    - name: Deploy to Staging Server (develop)
      if: github.ref_name == 'develop'
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}  
      run: |
        ssh -i ~/.ssh/github_hariship ubuntu@$SERVER_HOST \
          "cd ~/KnowledgeKeeperCore_Develop && \
          git pull origin develop && \
          docker-compose down && \
          docker-compose up --build -d"
          
    - name: Deploy to Production Server (main)
      if: github.ref_name == 'main'
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh -i ~/.ssh/github_hariship ubuntu@$SERVER_HOST \
          "cd ~/KnowledgeKeeperCore && \
          git pull origin main && \
          docker-compose down && \
          docker-compose up --build -d"