name: CI/CD for KnowledgeKeeperCore

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Prepare SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_hariship
        chmod 600 ~/.ssh/github_hariship

        ssh-keyscan -H ec2-18-189-31-171.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Debug SSH Connection
      env:
        SERVER_HOST: ec2-18-189-31-171.us-east-2.compute.amazonaws.com
      run: |
        ssh -vvv -i ~/.ssh/github_hariship.pub ubuntu@$SERVER_HOST echo "SSH connection successful"
      
    - name: Deploy to Staging Server (develop)
      if: github.ref_name == 'develop'
      env:
        SERVER_HOST: ec2-18-189-31-171.us-east-2.compute.amazonaws.com
      run: |
        ssh -i ~/.ssh/github_hariship.pub ubuntu@$SERVER_HOST \
          "cd ~/KnowledgeKeeperCore_Develop && \
          git pull origin develop && \
          docker-compose down && \
          docker-compose up --build -d"
          
    - name: Deploy to Production Server (main)
      if: github.ref_name == 'main'
      env:
        SERVER_HOST: ec2-18-189-31-171.us-east-2.compute.amazonaws.com
      run: |
        ssh -i ~/.ssh/github_hariship.pub ubuntu@$SERVER_HOST \
          "cd ~/KnowledgeKeeperCore && \
          git pull origin main && \
          docker-compose down && \
          docker-compose up --build -d"